name: Run Script on Commit

on:
  push:
    branches:
      - dev  # Change this to the branch you want to track commits on

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Change to repository root
        run: cd ${{ github.workspace }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Specify your desired Python version

      - name: Get the current version and run Python script
        run: |

          python scripts/processing_git_log.py
        

