name: Run Script on Commit


on:
  push:
    branches:
      - main  # Change this to the branch you want to track commits on
permissions:
  contents: write  # This allows the workflow to push changes

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Fetch all history so we can access all commit logs

    - name: Fetch all tags
      run: git fetch --tags

    - name: Clear GitHub Cache (Manual)
      run: |
        rm -rf ~/.cache/pip
        rm -rf venv

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build

    - name: Build package
      env:
        SETUPTOOLS_SCM_DEBUG: True
      run: python -m build